### ISSUE TITLE
NLB Support

### ISSUE THREAD

**Issue by mrthomaskim** [foremast/foremast#304] opened 2018-06-22 03:05 UTC
Ideally, I'd like to see if foremast can support NLB, Mainly to support Haproxies or possible SFTP server behind NLB

**Comment by jvasallo** [comment] 2018-08-16 06:16
Looks like Spinnaker may have added support in 1.9.0:
https://github.com/spinnaker/deck/commit/06ba3c5ad83186fd8d72d1361580d8f68b8742f7

**Comment by jvasallo** [comment] 2019-10-06 01:37
Closing this as its a duplicate of #279

**Closed** 2019-10-06 01:38 UTC
